# canonical data version: 2.2.0
# This file was generated by a script.

using Test

include("human-readable-time.jl")

@testset "should format correctly" begin
    @test humanreadable(0) == "00:00:00"
end

@testset "5 seconds" begin
    @test humanreadable(5) == "00:00:05"
end


@testset "60 seconds" begin
    @test humanreadable(60) == "00:01:00"
end

@testset "Almost a day" begin
    @test humanreadable(86399) == "23:59:59"
end
@testset "Many days" begin
    @test humanreadable(359999) == "99:59:59"
end
